version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        env_file: 
            - ./.env
        volumes: 
            - /usr/app/node_modules
            - ./:/usr/app
            
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /usr/app/node_modules
            - "./client:/usr/app:consistent"
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            -  3000:80

